xen: fixed up ps-xen and get-vnc-port scripts

diff --git a/xen/get-vnc-port b/xen/get-vnc-port
--- a/xen/get-vnc-port
+++ b/xen/get-vnc-port
@@ -5,4 +5,11 @@ then
   exit
 fi
 name=$1
-lsof -nPi | grep `ps -ef|grep qemu|grep "name $name"|awk '{ print $2}'`
+pid=$(ps -ef | grep "qemu" | grep "name $name" | awk '{ print $2}')
+
+if [[ -z "$pid" ]]; then
+  echo "ERROR: Failed to find qemu pid for '$name'"
+  exit 1
+fi
+
+lsof -nPi | grep "$pid"
